<template>
  <div class="page">
    <div class="page-header"><div><h2>工单与客户满意度</h2><p>安装、维修、咨询与投诉工单全流程闭环管理</p></div><el-space><el-button @click="exportReport">导出报表</el-button><el-button type="primary" @click="openCreate">新建售后工单</el-button></el-space></div>
    <el-row :gutter="16" class="stats"><el-col :span="6"><el-card><span>工单总数</span><b>{{ stats.total ?? 0 }}</b></el-card></el-col><el-col :span="6"><el-card><span>已结案</span><b>{{ stats.closed ?? 0 }}</b></el-card></el-col><el-col :span="6"><el-card><span>平均满意度</span><b>{{ stats.averageScore ?? '—' }}</b></el-card></el-col><el-col :span="6"><el-card><span>低满意度工单</span><b class="warn">{{ stats.lowScoreCount ?? 0 }}</b></el-card></el-col></el-row>
    <el-row :gutter="16" class="charts"><el-col :span="14"><el-card><div ref="trendEl" class="chart"/></el-card></el-col><el-col :span="10"><el-card><div ref="reasonEl" class="chart"/></el-card></el-col></el-row>
    <el-card><div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="工单号、客户、产品" @keyup.enter="load"/><el-select v-model="query.status" clearable placeholder="全部状态"><el-option v-for="s in statuses" :key="s" :label="s" :value="s"/></el-select><el-button @click="load">查询</el-button></div>
      <el-table :data="rows" v-loading="loading"><el-table-column prop="orderNo" label="工单号" min-width="170"/><el-table-column prop="customerName" label="客户" min-width="110"/><el-table-column prop="serviceType" label="服务类型" width="90"/><el-table-column prop="productName" label="产品" min-width="130"/><el-table-column prop="assigneeName" label="处理人" width="100"/><el-table-column prop="status" label="状态" width="95"><template #default="{row}"><el-tag>{{ row.status }}</el-tag></template></el-table-column><el-table-column label="操作" width="230" fixed="right"><template #default="{row}"><el-button link type="primary" @click="advance(row)" :disabled="!nextStatus(row.status)">{{ nextStatus(row.status) || '已完成' }}</el-button><el-button link @click="openDetail(row)">详情</el-button><el-button v-if="row.status === '已结案'" link type="warning" @click="openSatisfaction(row)">满意度</el-button></template></el-table-column></el-table>
      <el-pagination v-model:current-page="query.page" :page-size="query.size" :total="total" layout="total, prev, pager, next" @current-change="load"/></el-card>
    <el-dialog v-model="dialog" :title="editing ? '售后工单详情' : '新建售后工单'" width="720px"><el-form :model="form" label-width="90px"><el-row :gutter="16"><el-col :span="12"><el-form-item label="客户" required><el-input v-model="form.customerName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="服务类型" required><el-select v-model="form.serviceType" style="width:100%"><el-option v-for="t in serviceTypes" :key="t" :label="t" :value="t"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="联系人"><el-input v-model="form.customerContact"/></el-form-item></el-col><el-col :span="12"><el-form-item label="联系电话"><el-input v-model="form.customerPhone"/></el-form-item></el-col><el-col :span="12"><el-form-item label="产品名称"><el-input v-model="form.productName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="处理人"><el-input v-model="form.assigneeName"/></el-form-item></el-col></el-row><el-form-item label="服务地址"><el-input v-model="form.serviceAddress"/></el-form-item><el-form-item label="故障/诉求"><el-input v-model="form.faultDescription" type="textarea"/></el-form-item><el-form-item v-if="editing" label="回访记录"><el-input v-model="form.visitRecord" type="textarea"/></el-form-item></el-form><template v-if="editing"><el-divider content-position="left">状态流转记录</el-divider><el-timeline><el-timeline-item v-for="item in logs" :key="item.id" :timestamp="item.createdAt" placement="top"><b>{{item.beforeStatus||'创建'}} → {{item.afterStatus}}</b><span>　{{item.operatorName}} {{item.remark||''}}</span></el-timeline-item></el-timeline></template><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
    <el-dialog v-model="satisfactionDialog" title="客户满意度与低分闭环" width="520px"><el-form :model="satisfaction" label-width="100px"><el-form-item label="评分"><el-rate v-model="satisfaction.score" :max="5" show-score :disabled="!!satisfaction.id"/></el-form-item><el-form-item label="低分诱因"><el-select v-model="satisfaction.reasonDimension" clearable style="width:100%" :disabled="!!satisfaction.id"><el-option label="响应慢" value="响应慢"/><el-option label="维修不彻底" value="维修不彻底"/><el-option label="服务态度" value="服务态度"/><el-option label="其他" value="其他"/></el-select></el-form-item><el-form-item label="跟进负责人"><el-input v-model="satisfaction.responsibleName"/></el-form-item><el-form-item label="跟进结果"><el-input v-model="satisfaction.followUpResult" type="textarea"/></el-form-item><el-form-item v-if="satisfaction.score<=3" label="CAPA编号"><el-input v-model="satisfaction.capaNo" readonly placeholder="尚未发起CAPA"/><el-button v-if="satisfaction.id&&!satisfaction.capaNo" type="warning" link @click="startCapa">一键发起</el-button></el-form-item></el-form><template #footer><el-button @click="satisfactionDialog=false">取消</el-button><el-button type="primary" @click="saveScore">提交</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import * as echarts from 'echarts'
import { createAfterSalesCapa, createAfterSalesOrder, getAfterSalesLogs, getAfterSalesOrders, getAfterSalesStats, getSatisfaction, saveSatisfaction, transitionAfterSalesOrder, updateAfterSalesOrder, updateSatisfactionFollowUp, type AfterSalesOrder, type Satisfaction, type AfterSalesStats, type OrderLog } from '@/api/afterSales'
const statuses = ['新建','分配','处理中','待回访','已结案','取消'], serviceTypes = ['安装','维修','咨询','投诉'] as const
const query = reactive({ page: 1, size: 20, keyword: '', status: '' }), rows = ref<AfterSalesOrder[]>([]), total = ref(0), loading = ref(false), stats = ref<Partial<AfterSalesStats>>({})
const dialog = ref(false), editing = ref(false), satisfactionDialog = ref(false), selectedId = ref<number>(), logs=ref<OrderLog[]>([]),trendEl=ref<HTMLElement>(),reasonEl=ref<HTMLElement>();let trendChart:echarts.ECharts|undefined,reasonChart:echarts.ECharts|undefined
const empty = (): AfterSalesOrder => ({ customerName: '', serviceType: '安装', customerContact: '', customerPhone: '', productName: '', assigneeName: '', serviceAddress: '', faultDescription: '', visitRecord: '' })
const form = reactive<AfterSalesOrder>(empty()), satisfaction = reactive<Satisfaction>({ score: 5, reasonDimension: '', responsibleName: '', followUpResult: '' })
async function load(){ loading.value=true; try { const [list, summary] = await Promise.all([getAfterSalesOrders(query), getAfterSalesStats()]); rows.value=list.data?.list || []; total.value=list.data?.total || 0; stats.value=summary.data || {};await nextTick();renderCharts() } finally { loading.value=false } }
function openCreate(){ editing.value=false; Object.assign(form, empty()); dialog.value=true }
async function openDetail(row: AfterSalesOrder){ editing.value=true; Object.assign(form, row);logs.value=row.id?(await getAfterSalesLogs(row.id)).data||[]:[]; dialog.value=true }
async function save(){ if(!form.customerName) return ElMessage.warning('请填写客户名称'); if(editing.value && form.id) await updateAfterSalesOrder(form.id, form); else await createAfterSalesOrder(form); ElMessage.success('保存成功'); dialog.value=false; load() }
function nextStatus(status?: string){ return ({'新建':'分配','分配':'处理中','处理中':'待回访','待回访':'已结案'} as Record<string,string>)[status || ''] }
async function advance(row: AfterSalesOrder){ const target=nextStatus(row.status); if(!target || !row.id) return; await transitionAfterSalesOrder(row.id,target); ElMessage.success(`已流转至${target}`); load() }
async function openSatisfaction(row: AfterSalesOrder){ selectedId.value=row.id; const existing=row.id?(await getSatisfaction(row.id)).data:undefined;Object.keys(satisfaction).forEach(k=>delete (satisfaction as any)[k]);Object.assign(satisfaction,existing||{score:5,reasonDimension:'',responsibleName:'',followUpResult:''}); satisfactionDialog.value=true }
async function saveScore(){ if(!selectedId.value) return; satisfaction.id?await updateSatisfactionFollowUp(selectedId.value,satisfaction):await saveSatisfaction(selectedId.value,satisfaction); ElMessage.success('满意度记录已提交'); satisfactionDialog.value=false; load() }
async function startCapa(){if(!selectedId.value)return;const r=await createAfterSalesCapa(selectedId.value);satisfaction.capaNo=r.data?.capaNo;ElMessage.success(`CAPA ${satisfaction.capaNo||''} 已创建并回写`);load()}
function renderCharts(){const months=Object.keys(stats.value.monthlyTrend||{}),reasons=Object.keys(stats.value.lowScoreReasons||{});trendChart=trendChart||echarts.init(trendEl.value!);trendChart.setOption({title:{text:'售后工单趋势',textStyle:{fontSize:15}},tooltip:{trigger:'axis'},xAxis:{type:'category',data:months},yAxis:{type:'value',minInterval:1},series:[{type:'line',smooth:true,areaStyle:{},data:months.map(x=>stats.value.monthlyTrend?.[x]||0)}]});reasonChart=reasonChart||echarts.init(reasonEl.value!);reasonChart.setOption({title:{text:'低分诱因',textStyle:{fontSize:15}},tooltip:{trigger:'item'},series:[{type:'pie',radius:['38%','68%'],data:reasons.map(x=>({name:x,value:stats.value.lowScoreReasons?.[x]||0}))}]})}
function exportReport(){const lines=[['工单号','客户','服务类型','产品','处理人','状态'],...rows.value.map(x=>[x.orderNo,x.customerName,x.serviceType,x.productName,x.assigneeName,x.status])];const blob=new Blob(['\ufeff'+lines.map(x=>x.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`售后工单报表-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
onBeforeUnmount(()=>{trendChart?.dispose();reasonChart?.dispose()})
onMounted(load)
</script>
<style scoped>
.page{padding:20px}.page-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:18px}.page-header h2{margin:0;color:#1b3a5b}.page-header p{margin:6px 0 0;color:#8c9ba8}.stats,.charts{margin-bottom:16px}.stats .el-card span{color:#8c9ba8;font-size:13px}.stats b{display:block;font-size:26px;margin-top:8px;color:#1b3a5b}.stats b.warn{color:#d97706}.chart{height:250px}.toolbar{display:flex;gap:12px;margin-bottom:16px}.toolbar .el-input{width:260px}.toolbar .el-select{width:130px}.el-pagination{margin-top:16px;justify-content:flex-end}
</style>
