<template>
  <div class="page">
    <header><h1>工装管理</h1></header>
    <el-tabs v-model="tab">
      <el-tab-pane label="工装台账管理" name="ledger">
        <div class="bar"><el-input v-model="keyword" placeholder="工装编号、名称"/><el-button @click="load">查询</el-button><el-button type="primary" @click="open()">新建工装</el-button></div>
        <el-table :data="rows" v-loading="loading" stripe><el-table-column prop="toolingCode" label="编号"/><el-table-column prop="toolingName" label="名称"/><el-table-column label="采购日期/成本"><template #default="{row}">{{row.purchaseDate||'—'}}<br/>¥ {{row.cost??'—'}}</template></el-table-column><el-table-column prop="status" label="状态"/><el-table-column label="操作" width="350"><template #default="{row}"><el-button link @click="open(row)">编辑</el-button><el-button link @click="qr(row)">二维码</el-button><el-button link @click="bind(row)">BOM/工艺</el-button><el-button link @click="version(row)">版本</el-button><el-button link @click="usage(row)">使用</el-button></template></el-table-column></el-table>
      </el-tab-pane>
      <el-tab-pane label="工装维修和保养" name="maintenance">
        <div class="bar"><el-button type="primary" @click="remind">到期保养提醒</el-button><el-button @click="stats">故障统计图</el-button></div><div ref="chart" class="chart"/><el-table :data="maint"><el-table-column prop="dueDate" label="到期日/统计"/><el-table-column prop="faultDescription" label="故障类型"/><el-table-column prop="rootCause" label="根因"/><el-table-column prop="status" label="状态/次数"/></el-table>
      </el-tab-pane>
    </el-tabs>
    <el-dialog v-model="formOpen" title="工装台账" width="700px"><el-form :model="form" label-width="90px"><el-row><el-col :span="12"><el-form-item label="工装编号"><el-input v-model="form.toolingCode"/></el-form-item></el-col><el-col :span="12"><el-form-item label="工装名称"><el-input v-model="form.toolingName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="采购日期"><el-date-picker v-model="form.purchaseDate" type="date" value-format="YYYY-MM-DD"/></el-form-item></el-col><el-col :span="12"><el-form-item label="采购成本"><el-input-number v-model="form.cost" :min="0" :precision="2"/></el-form-item></el-col><el-col :span="12"><el-form-item label="适用产品"><el-input v-model="form.applicableProduct"/></el-form-item></el-col><el-col :span="12"><el-form-item label="适用工序"><el-input v-model="form.applicableProcess"/></el-form-item></el-col><el-col :span="12"><el-form-item label="位置"><el-input v-model="form.storageLocation"/></el-form-item></el-col><el-col :span="12"><el-form-item label="责任人"><el-input v-model="form.keeperName"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="formOpen=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
    <el-dialog v-model="qrOpen" title="工装一物一码" width="400px"><div class="q"><h3>{{qrTitle}}</h3><img :src="qrUrl"/><p>{{qrValue}}</p></div><template #footer><el-button @click="window.print()">打印</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import{nextTick,onMounted,reactive,ref}from'vue';import{ElMessage,ElMessageBox}from'element-plus';import*as echarts from'echarts';import{toDataURL}from'qrcode';import{addToolingUsage,createTooling,createToolingVersion,getTooling,getToolingBindings,getToolingFailureStats,getToolingReminders,saveToolingBindings,updateTooling,type ToolingAsset}from'@/api/supplierTooling';
const window=globalThis.window,tab=ref('ledger'),keyword=ref(''),rows=ref<ToolingAsset[]>([]),loading=ref(false),formOpen=ref(false),qrOpen=ref(false),qrUrl=ref(''),qrTitle=ref(''),qrValue=ref(''),maint=ref<any[]>([]),chart=ref<HTMLElement>();const blank=():ToolingAsset=>({toolingCode:'',toolingName:'',toolingType:'治具',status:'在用',versionNo:'V1.0'}),form=reactive<ToolingAsset>(blank());
async function load(){loading.value=true;try{const r=await getTooling({page:1,size:100,keyword:keyword.value});if(r.code===0)rows.value=r.data.list||[]}finally{loading.value=false}}function open(x?:ToolingAsset){Object.assign(form,x?{...x}:blank());formOpen.value=true}async function save(){const r=form.id?await updateTooling(form.id,form):await createTooling(form);if(r.code===0){formOpen.value=false;load()}}async function qr(x:ToolingAsset){qrTitle.value=x.toolingName;qrValue.value=x.qrCode||`QMS-TL-${x.toolingCode}`;qrUrl.value=await toDataURL(qrValue.value,{width:280});qrOpen.value=true}async function usage(x:ToolingAsset){const{value}=await ElMessageBox.prompt('使用次数','登记使用');await addToolingUsage(x.id!,Number(value));load()}async function bind(x:ToolingAsset){const r=await getToolingBindings(x.id!),{value}=await ElMessageBox.prompt('每行：BOM/工艺路线|产品|BOM|工序','关联',{inputValue:(r.data||[]).map(v=>`${v.bindingType}|${v.productCode||''}|${v.bomCode||''}|${v.processName||''}`).join('\n'),inputType:'textarea'});await saveToolingBindings(x.id!,value.split('\n').filter(Boolean).map((v:string)=>{const[a,b,c,d]=v.split('|');return{bindingType:a as'BOM'|'工艺路线',productCode:b,bomCode:c,processName:d}}));ElMessage.success('已保存')}async function version(x:ToolingAsset){const{value}=await ElMessageBox.prompt('版本|类型|说明','版本变更');const[a,b,c]=value.split('|');await createToolingVersion(x.id!,{versionNo:a,changeType:b,changeDescription:c});load()}async function remind(){const r=await getToolingReminders();if(r.code===0)maint.value=r.data}async function stats(){const r=await getToolingFailureStats();if(r.code===0){maint.value=r.data.map(x=>({dueDate:'故障统计',faultDescription:x.faultType,rootCause:x.rootCause,status:`${x.count} 次`}));await nextTick();echarts.init(chart.value!).setOption({xAxis:{type:'category',data:r.data.map(x=>x.faultType)},yAxis:{type:'value'},series:[{type:'bar',data:r.data.map(x=>x.count)}]})}}
onMounted(load)
</script>
<style scoped>.page{padding:24px}.bar{display:flex;gap:10px;margin:14px 0}.bar .el-input{width:250px}.chart{height:260px}.q{text-align:center}.q img{width:280px}</style>
