<template>
  <div class="page">
    <header><h1>供应商基础管理</h1><p>维护供应商绩效评价、关键物料 SPC 评价及 A/B/C/D 分级建议。</p></header>
    <section class="notice"><b>绩效说明</b><span>供应商排名、趋势图和柏拉图继续在“来料数据管理”中查看，本模块不与工装管理联动。</span></section>
    <section class="card"><div class="card-header"><div><h2>供应商绩效评价</h2><span>五项指标 + 关键物料 SPC 评价</span></div><el-button type="primary" @click="openForm()">新增评价</el-button></div>
      <el-table :data="rows" v-loading="loading" stripe empty-text="暂无供应商评价记录"><el-table-column label="供应商" min-width="160"><template #default="{ row }">{{ supplierName(row.supplierId) }}</template></el-table-column><el-table-column prop="assessmentPeriod" label="考核周期" width="115"/><el-table-column label="五项指标" min-width="250"><template #default="{ row }"><span v-for="item in metrics(row)" :key="item" class="metric">{{ item }}</span></template></el-table-column><el-table-column prop="spcAssessment" label="SPC评价" width="150"/><el-table-column label="等级" width="85"><template #default="{ row }"><el-tag :type="gradeType(row.grade)">{{ row.grade || '—' }}</el-tag></template></el-table-column><el-table-column prop="shareSuggestion" label="采购份额建议" width="125"/><el-table-column prop="auditFrequency" label="审核频次" width="110"/><el-table-column prop="admissionSuggestion" label="准入建议" width="115"/><el-table-column label="操作" width="80" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="openForm(row)">编辑</el-button></template></el-table-column></el-table>
    </section>
    <el-dialog v-model="visible" :title="form.id ? '编辑供应商评价' : '新增供应商评价'" width="760px" destroy-on-close><el-form :model="form" label-width="105px"><el-row :gutter="16"><el-col :span="12"><el-form-item label="供应商" required><el-select v-model="form.supplierId" filterable style="width:100%"><el-option v-for="s in suppliers" :key="s.id" :value="s.id" :label="`${s.supplierName} (${s.supplierCode})`"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="考核周期" required><el-input v-model="form.assessmentPeriod" placeholder="如：2026-Q3"/></el-form-item></el-col></el-row><el-divider content-position="left">五项绩效指标（%）</el-divider><el-row :gutter="16"><el-col v-for="field in metricFields" :key="field.key" :span="8"><el-form-item :label="field.label"><el-input-number v-model="form[field.key]" :min="0" :max="100" :precision="2" style="width:100%"/></el-form-item></el-col></el-row><el-form-item label="SPC评价"><div style="display:flex;gap:8px;width:100%"><el-select v-model="form.spcAssessment" style="flex:1"><el-option label="过程稳定，能力满足" value="过程稳定，能力满足"/><el-option label="存在波动，需跟踪" value="存在波动，需跟踪"/><el-option label="样本不足，不评价" value="样本不足，不评价"/></el-select><el-button @click="loadSpcEvidence">自动读取SPC</el-button></div></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存并生成等级建议</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { createAssessment, getAssessments, getSuppliers, getSupplierSpcEvidence, updateAssessment, type SupplierAssessment, type SupplierItem } from '@/api/supplierTooling'
const suppliers = ref<SupplierItem[]>([]), rows = ref<SupplierAssessment[]>([]), loading = ref(false), saving = ref(false), visible = ref(false)
const empty = (): SupplierAssessment => ({ supplierId: 0, assessmentPeriod: '', spcAssessment: '样本不足，不评价' })
const form = reactive<SupplierAssessment>(empty())
const metricFields = [{ key: 'qualifiedRate' as const, label: '来料合格率' }, { key: 'defectRate' as const, label: '不良率' }, { key: 'rectificationRate' as const, label: '整改及时率' }, { key: 'deliveryRate' as const, label: '交付及时率' }, { key: 'complianceRate' as const, label: '合规率' }]
const supplierName = (id: number) => suppliers.value.find(s => s.id === id)?.supplierName || `供应商 #${id}`
const pct = (value?: number) => value == null ? '—' : `${Number(value).toFixed(1)}%`
const metrics = (row: SupplierAssessment) => [`来料 ${pct(row.qualifiedRate)}`, `不良 ${pct(row.defectRate)}`, `整改 ${pct(row.rectificationRate)}`, `交付 ${pct(row.deliveryRate)}`, `合规 ${pct(row.complianceRate)}`]
const gradeType = (grade?: string) => grade === 'A' ? 'success' : grade === 'B' ? 'primary' : grade === 'C' ? 'warning' : 'danger'
async function load() { loading.value = true; try { const r = await getAssessments(); if (r.code === 0) rows.value = r.data.list || [] } finally { loading.value = false } }
function openForm(row?: SupplierAssessment) { Object.assign(form, row ? { ...row } : empty()); visible.value = true }
async function loadSpcEvidence() { if (!form.supplierId) return ElMessage.warning('请先选择供应商'); const r = await getSupplierSpcEvidence(form.supplierId); if (r.code === 0) { form.spcAssessment = r.data.assessment; ElMessage.success(`${r.data.message}${r.data.minCpk == null ? '' : `，最低 Cpk：${r.data.minCpk}`}`) } }
async function save() { if (!form.supplierId || !form.assessmentPeriod) return ElMessage.warning('请选择供应商并填写考核周期'); saving.value = true; try { const r = form.id ? await updateAssessment(form.id, form) : await createAssessment(form); if (r.code === 0) { ElMessage.success('评价已保存，等级建议已更新'); visible.value = false; load() } } finally { saving.value = false } }
onMounted(async () => { const r = await getSuppliers(); if (r.code === 0) suppliers.value = r.data.list || []; load() })
</script>

<style scoped>.page{max-width:1440px;margin:0 auto;padding:24px 32px 48px;color:#263746}header{border-bottom:1px solid #dbe4e8;padding-bottom:16px;margin-bottom:18px}h1{margin:0;color:#163c5b;font-size:24px}header p,.card-header span{margin:6px 0 0;color:#71808a;font-size:13px}.notice{display:flex;gap:14px;background:#f2f8fb;border:1px solid #d6e8f0;color:#456270;padding:10px 14px;border-radius:6px;font-size:13px;margin-bottom:14px}.notice b{color:#25728a}.card{background:#fff;border:1px solid #e2e8eb;border-radius:8px;padding:16px}.card-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.card-header h2{margin:0;color:#163c5b;font-size:16px}.metric{display:inline-block;font-size:11px;background:#f4f7f8;color:#526772;border-radius:3px;padding:2px 5px;margin:2px}@media(max-width:800px){.page{padding:16px}.notice{display:block}.notice span{display:block;margin-top:6px}}</style>
